networks:
  backend:
    driver: bridge
    name: backend
    external: true

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      ALLOW_IP_RANGE: '0.0.0.0/0'

  backend:
    container_name: backend
    networks:
      - backend
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_DIALECT: "${DB_DIALECT}"
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/app/
      - node_modules:/var/app/node_modules
    ports:
      - 3000:3000
    working_dir: /var/app
volumes:
  db_data:
    name: "scheduler-postgres"
  node_modules:
    name: "scheduler-node-modules"